### ISSUE TITLE
Unable to checkout NSBencodeSerialization

### ISSUE THREAD

**Issue by mithical** [Qata/BarMagnet#10]
Been trying for a bit now but can't seem to build BarMagnet at all. I realized by looking at the Terminal that while using the ```git submodule update --init --recursive``` it didn't fully install completely.

![screen shot 2015-01-21 at 12 31 34 pm](https://cloud.githubusercontent.com/assets/3520542/5842381/f66082b2-a169-11e4-8c53-ae3e9f718bfe.png)

Aside from that, I'm also getting a constant TestFlight-related error.

![screen shot 2015-01-21 at 12 32 12 pm](https://cloud.githubusercontent.com/assets/3520542/5842384/03754c08-a16a-11e4-9ffe-0e9a727007ff.png)

**Comment by Qata** [comment]
The cloning issue is now fixed. I'll add in the TestFlight header when I get home from work, or possibly ifdef it out so that other people don't need to deal with it.

**Comment by Qata** [comment]
The version I just pushed both has the TestFlight header and lib, but also has a preprocessor checking flag that will let you easily enable/disable TestFlight via Xcode's preprocessor macros.
