### ISSUE TITLE
Quit After Add

### ISSUE THREAD

**Issue by profplump** [Qata/BarMagnet#11]
I'd love a mode that launches on magnet URL requests, adds the torrent to the configured server, and then immediately exits. I'm sure the monitoring features are useful for many people, but I use the program strictly to add torrents it would be nice if the program supported that usage.

To allow standard usage and preference editing, the exit-after-add effect would only be triggered when the program was launched with a URL request.

**Comment by Qata** [comment]
That sounds like it'd work better as a Safari extension instead of a launch/quit feature.
Also with iOS 9, you can now just tap "Back to Safari" in the menu bar if you were launched into BarMagnet by Safari.

**Comment by profplump** [comment]
Would a Safari extension allow other programs to resolve magnet URLs? My primary usage of BarMagnet is via the `open` CLI command.

**Comment by Qata** [comment]
Oh you're talking about the OS X app. That app's code is long lost, this repository is for the iOS app.
