### ISSUE TITLE
Apple Watch App

### ISSUE THREAD

**Issue by tiferrei** [Qata/BarMagnet#13]
Hi, I am new to GitHub and all this open source thing but what's the "legal", "right" way of editing this app? I would like to add an attached apple watch app for it, something really simple, just to show the torrent progress or download speed.

Thanks,
Tiago Ferreira

**Comment by Qata** [comment]
Forking the project and then editing that locally is the way to go about it, there's no legal ramifications for that. Send a pull request when you're done if you'd like your changes to be in the upstream branch.

**Comment by tiferrei** [comment]
Thanks, I tried completing the appIcon image asset but it doesn't allows me to commit and sync.
It says I have no permission.

![screen shot 2015-10-07 at 21 51 28](https://cloud.githubusercontent.com/assets/8849915/10350751/a9b1f8ce-6d3d-11e5-89be-8886103edff6.png)

**Comment by Qata** [comment]
You'll need to fork BarMagnet to your account and set the upstream repo in git to reflect that.
