### ISSUE TITLE
Authentication failure with self-signed certificate 

### ISSUE THREAD

**Issue by frriction** [Qata/BarMagnet#17]
I am new to this iphone app compiling and I believe I did it correctly but I am getting following error with my self-signed certificate with my rtorrent/rutorrent set up.
Currently I am using version from cydia which shows error but gets connected but compiled version does not get connected and shows host as offline. 

Here is the Image of error message.

![error]
(https://i.imgur.com/rTZv3E3.jpg)

**Comment by Qata** [comment]
The version on Cydia uses a workaround that no longer works when compiling against the latest libs.
Unfortunately, to use the version on Github, you’ll need to use a CA signed cert or switch to regular HTTP.

**Comment by frriction** [comment]
I have found the free signed certificate provider and it works with BM. 
https://letsencrypt.org/howitworks/
Now only issue is I can not use BM in my local network with LAN IP.

**Comment by Qata** [comment]
The price you pay for using TLS is that it won't work when accessing via anything but the registered and qualified DNS name or IP address.
You'll need to use your DNS name even when at home.

**Comment by frriction** [comment]
I am using nginx for rutorrent, so I copied the server file and hosted a new server with different port for LAN without https. 
I have upnp disabled so outside world can not see my rutorrent through that port.
