### ISSUE TITLE
Require rpc.php for ruTorrent

### ISSUE THREAD

**Issue by Griever92** [Qata/BarMagnet#21]
Installation and configuration instructions indicate that rpc.php is required for use with ruTorrent implementations.

Unfortunately, the address provided for this is now invalid.
https://github.com/Qata/TruTorrent

**Comment by Qata** [comment]
Use ruTorrent HTTPRPC, that's a maintained plugin.

**Comment by Griever92** [comment]
Cheers, 
Thank you
