### ISSUE TITLE
iOS 9 - Crashes on adding a .torrent - magnet working fine (built myself)

### ISSUE THREAD

**Issue by craigerrington** [Qata/BarMagnet#24]
Hey, I built this in xcode after adding in the fixes mentioned here: https://github.com/Qata/BarMagnet/issues/20

Works great connecting to my deluge instance (although not transmission for some reason).. I've got it handling magnet links and working fine.

However, when starting in safari with a torrent file, and choosing 'copy to barmagnet' from share page, barmagnet opens and then just dies.

Any ideas?

**Comment by ismaelab** [comment]
Same issue here. I have Transmission working properly but when I use the option from Sarafi to Copy to Barmagnet, it opens and crash immediately.

**Comment by yozik04** [comment]
For me it works for couple of days after rebuild & reinstall. Then it starts crashing again. iOS does not write any crash logs. Very hard to debug.
