### ISSUE TITLE
Possible to add a simple password saver to the browser for private torrents sites.

### ISSUE THREAD

**Issue by loneyliver** [Qata/BarMagnet#27]
Occasionally my tracker sites will log me out and some passwords I have are crazy long. Any way to add a simple password manager to the browser?

Also is there a tutorial anywhere where I can convert the Github files here to an ipa so I can add it thru cydia impactor on a non jailbroken phone.

Thanks

**Comment by Qata** [comment]
Use Safari and select "open in BarMagnet" when you long press on magnet links.
It'd be very insecure for BarMagnet to try and save your passwords, so I'd just recommend leaving it to Safari.
