### ISSUE TITLE
1.9.2 on ipad pro 10.2 has strange behavior when adding torrent

### ISSUE THREAD

**Issue by loneyliver** [Qata/BarMagnet#29]
1.9.2 installs fine on 10.2 ipad pro. It runs and adds torrents from websites just fine but the usual green banner at the top that indicates that you've added a torrent seems to fly from the bottom of the screen to the top in a split second without pausing to show itself.

**Comment by Qata** [comment]
Ah yeah that's an old library that wasn't built to support such huge screen sizes.

**Comment by Qata** [comment]
Just updated to the latest version of `TSMessage`, let me know if that fixes it.

**Comment by loneyliver** [comment]
Thanks... works great now
