### ISSUE TITLE
BarMagnet No Longer Works with Deluge 3.1.14

### ISSUE THREAD

**Issue by Protosun** [Qata/BarMagnet#30]
BarMagnet no longer connects with the latest version of Deluge 3.1.14

The error may be related to Sonarr issue described here: https://github.com/Sonarr/Sonarr/issues/1738

Deluge 3.1.13 does work as an alternative.

**Comment by mrjonny2** [comment]
Do you get an unable to authenticate error?

**Comment by reidrankin** [comment]
Same here. "Unable to authenticate."

**Comment by reidrankin** [comment]
Looks like universalPOSTSetting in Deluge.m needs [request setValue:@"application/json" forHTTPHeaderField:@"Content-Type"]; right before the retval = [request copy]; line.

(Sorry, on my phone, can't really work up a PR at the moment!)
