### ISSUE TITLE
Need to be able to customize Transmission URL prefix

### ISSUE THREAD

**Issue by galori** [Qata/BarMagnet#34]
I added my transmission instance but it is not listing any torrents. I think its because my Transmission Web UI is at `<hostname>/username/transmission/web/` but the app doesn't let me specify this path and just assumes its always at `<hostname>/transmission/web/`.

There is the "Directory" field with Transmission, but it doesn't seem to be affecting anything - so I'm assuming thats the directory for creating new torrents or something like that - and not the web URL.

**Comment by galori** [comment]
After a bit of Charles HTTP tracing, I realized the app is trying to connect to `<hostname>/transmission/rpc` but its getting a 404, because it should be connecting to `<hostname>/<username>/transmission/rpc` which I have verified works.

**Comment by Qata** [comment]
@galori Fixed in c7cb2ba
You can now set a relative path, just set it as whatever your username is.
