### ISSUE TITLE
Having some trouble with installation

### ISSUE THREAD

**Issue by evilmanimani** [Qata/BarMagnet#35]
I'm currently running 1.9.2 (1) and I'm wanting to update since I'm experiencing the issue described here: https://github.com/Qata/BarMagnet/issues/30 however but I know next to nothing about development, so the installation instructions don't really mean much to me. I tried running the command in Windows, and got this: 
C:\BarMagnet-master>git submodule update --init --recursive
fatal: Not a git repository (or any of the parent directories): .git

I'm probably doing it wrong though. Is there an updated IPA I can grab, or an official Cydia repo or anything? Sorry to be a pain, I found very little about this in the course of Googling and searching Reddit. Cheers.

**Comment by Qata** [comment]
No there isn't any provided IPAs, it needs to be built by you or someone you know with a Mac running Xcode.

**Comment by evilmanimani** [comment]
Ah figured it was something like that, yeah I don't own a Mac unfortunately, (or know anyone with one I could use) guess I'll keep an eye out to see if it surfaces on some repo. Thanks.
