### ISSUE TITLE
Installation method?

### ISSUE THREAD

**Issue by galori** [Qata/BarMagnet#36]
Would be useful to have some hints as to how most people (or the recommended) install method of this app in the README.  Is there an official cydia repo, or do most people just build it with xcode?

**Comment by galori** [comment]
Ok sorry just saw this which was literally closed 16 hours ago: 

https://github.com/Qata/BarMagnet/issues/35

Do you think its appropriate to mention this in the README? if so I can create a PR.

**Comment by Qata** [comment]
I just updated it with a section about Xcode.
