### ISSUE TITLE
qBittorrent Web UI doesn't work on 1.9.2 (latest build)

### ISSUE THREAD

**Issue by qauff** [Qata/BarMagnet#39]
my server is running qBittorrent 3.3.16 and deluge 1.3.12 (I've got an NGINX reverse proxy providing HTTPS access to both). BarMagnet works with my deluge set up, but not qBittorrent. BarMagnet throws the error: "Unable to authenticate. No error info provided, are you sure that's the right port?"
I'm 100% certain it's the right port. 

Here's a screenshot of the error.

![Screenshot](https://lh3.googleusercontent.com/yvcP3sJugkiKGVIZP5dcM8BdUwn76SOZP8PT-a_-zTZjQpghnjgBKJPSKlsZ3L9nCqUjpc6baHLJ5rVS-Bj1It8y-3wiswGhTjVcsvd2kZI5XViGO4pHjCQcAc2l7BgvWSfKWzOH68rY4rnr2oHMCsrHImd1iMyAZX3x6iOFcGXYpnHxXArkaCXZbwC0Uk7O8y6JKwEk_IX6_02HyAkOfz_PO7H_bhBKub1zvwWzOZec4vmpLQM22ewJ-jokbuo1GQ7O0JYmgKQ_RVYWk6GLAlI-YQrsGAcNaw-ANQK6nUcX0nWjybg7fDfLzuE8OD6dKnm35LiLeWDM5nHlJTNcZPApgxRaDTmkZEVWutFVVWrgwPYv8vLdF1grnuWQXaQrElQ1yRZJuT4TE2hQd434vR4AmVfzCR3_mTUzaVGVms5EN9Izb9shNAh3KCQXOk7YhrynSI7A-ayXOgEKWwnMCwt4h9KLvAjLX42AHrYTAOLDTIXRUArrjDo3xx4BE3wuhMNQVm4ExbhOwP0xuUwzngCeBbpTvumK2wSAqWLl6uQh4-SCp0mmlKfUvKAWINCdYX9YsF52pr40wy9-5uvoNpLHAjwB_ht08LwVRPcLjR7gEHvk-_ZY-f3Rd_z-secg4HSEmFSU3ybD3ejRxVDvS0iauBrwl9m6Jo4v=w463-h822-no)

the Open UI button shows the correct URL:

[Open UI](https://lh3.googleusercontent.com/HzYxajmAnJsyv81EXO5mC-Z70S2LhVyRJofJEvrfVTRWL3AWYceAqbpJhMTqo7ZqGL1c977lJHbwkInWkD9Wkd3fWPUDwdmGpX5lVVPsimIFkGcqlzaxg98fNWAHASF_AYM7Gnp8lzbwz34JRLa-coDWb89Z_5sfvwToBdERgrrz6A6B2WNvwYh757VXfPzDxHgsz789udl37s9OEX5BtNqwj5BY27VHhcKE8yApGsmF5r5tb4d82swoSfohSFTZ3KWf3ktaTq4cFS1zmdFDEfDLCiGUhUQRPbio00CaJCYkEMZ7ZaWqq2aRwCGO22kPBNDAEBA1f9pj0X9zo62lsd2DaIhxDwjvBHTtECgLIUP8DLN4HR7ReU3PZcNXPoQ3IkXSq1bjrrbcH0s99fnM85mUPv4mPI9ppjhesQ1CgRfMlhaawsh74AfToStSYL3OhJuCjcV8dtpGorSlpsOKw2QcAAZ6oTioPpOuR1x-kk39d419Ps08eYvP9V6jTFTnXSiG1dydmhQjMQG_X1Mpy5r9OxE9qxVF6bRPdy-BPF_9fgHMW0yHfIEVN-T7IoxdhZZWNpp-TuOixlxp915D_PMo0F7Vx4RD4je1GLVmLGc=w463-h822-no)

Any ideas what could be wrong, or what I could try to make this work?

**Comment by Qata** [comment]
It's probable that the version you're using of qBittorrent isn't compatible with the version I implemented against. qBittorrent was definitely one of the worse when it came to APIs so I wouldn't be surprised.

**Comment by qauff** [comment]
@Qata yeah I remember they added quite a bit of CORS protection in 3.3.13, that broke things for API users and people reverse proxying like me, so that's likely the cause here too :/

**Comment by Qata** [comment]
@qauff Are you okay with just switching to Deluge? Honestly it was just a pain to implement support for qBittorrent in the first place so I might remove it if it's now broken.

**Comment by mingpowershifter** [comment]
@Qata Hm.. I could do that yeah. I'd prefer not to cause I do have deluge set up for something else. I suppose I could have two deluges, might be tricky!! But doable. No biggie if qBittorrent is too much of a pain. I get it, they change a lot!

**Comment by qauff** [comment]
@Qata Hm.. I could do that yeah. I'd prefer not to cause I do have deluge set up for something else. I suppose I could have two deluges, might be tricky!! But doable. No biggie if qBittorrent is too much of a pain. I get it, they change a lot!

**Comment by jab11** [comment]
@Qata qBittorrent changes were mostly about authentication and some data formatting, merge my pull request #41  ?

**Comment by Qata** [comment]
Closed via #41
