### ISSUE TITLE
Possible to update for Iphone X

### ISSUE THREAD

**Issue by loneyliver** [Qata/BarMagnet#43]
I know its not an issue but an update to take advantage of the longer Iphone X screen would be great. Thanks for a great app!!!

**Comment by jab11** [comment]
It works on my X without any changes, just recompiling in new Xcode.

**Comment by loneyliver** [comment]
are you getting a full filled in screen from top to bottom? or just the windowed  screen that is the size made for iphone 7  with black bars at the top and bottom?

**Comment by jab11** [comment]
Yes, full screen, regular X form with top notch and everything.
Apps that use launch storyboards support this screen automatically with xcode 9

**Comment by loneyliver** [comment]
ok i see now...thanks for your quick replies. most of the time i have downloaded this from various sites and then just installed. This is my third time building and app thru Xcode but not this app. I have limited knowledge so I may fail at this. I have downloaded the project and only hung up on what the instructions say.

After downloading, cd to the root folder and run git submodule update --init --recursive to initialise all submodules used by this project and by the projects that this project uses

I have to imaging this means using terminal to cd to the project folder? I am just not sure which one is the root folder to do this in? Any chance you can point me in the right direction. I think after this I maybe able to manage the rest.

Thank you for any help

**Comment by jab11** [comment]
yes, use terminal, cd to the directory where you downloaded the project. the directory will contain LICENSE.txt README.md and BarMagnet.xcodeproj and other stuff.
from there, run that submodule command. Then open BarMagnet.xcodeproj and check that Launch Storyboard is selected in Target. I'm running it on X with that configuration.

**Comment by loneyliver** [comment]
just got it working and installed, looks good and working great..  .. thanks for your help

**Comment by loneyliver** [comment]
Hey Jab11, is it possible to make the browser within barmagnet  to behave like safari in regards to the disappearing bottom tab giving like a full screen edge to edge. Seems to help in landscape too. Thanks again

**Comment by Qata** [comment]
This is a different issue and no it is not, it uses an old SVWebViewController at the moment and that'd need to be replaced.

**Comment by loneyliver** [comment]
Thank Qata... Not a big deal...Was just wondering how involved it would be...
