### ISSUE TITLE
Building BarMagnet on Xcode 9.1

### ISSUE THREAD

**Issue by miroesq** [Qata/BarMagnet#44]
I am trying to install BarMagnet on my iPhone X, but am unable to build the project.

Error 1: Missing dependency target "NSBencodeSerialization (from NSBencodeSerialization.xcodeproj)"

Error 2: #import "SVModalWebViewController.h"        'SVModalWebViewController.h' file not found

While I have a developer account, I have no technical skills. Is there a tutorial on how to build BarMagnet so that I may install it?

I already tried installing the unsigned ipa app and using cydia impactor, but am getting an error there as well when I try to install it.

ipa.cpp:444
cannot find .app/Info.plist

**Comment by Qata** [comment]
Sounds like you didn’t run the commands in the README to knit the sub modules?

**Comment by miroesq** [comment]
I downloaded the zip file BarMagnet-master and unzipped it in my downloads folder. I then opened a terminal command and cd to Downloads/BarMagnet-master. I then ran that command and received the following error:

fatal: Not a git repository (or any of the parent directories): .git

**Comment by Qata** [comment]
Ah yeah the zip doesn’t preserve git. You’ll need to install git and use that to clone it down. 

Regards,
Charlotte

**Comment by miroesq** [comment]
Can't thank you enough fr the help. Worked like a charm. Had to go into the project and change the signing certificate first, but figured that out after a few tries, that's how much of a noob I am. Again, thanks a lot.
