### ISSUE TITLE
Option to Manually Trust Self-Signed SSL?

### ISSUE THREAD

**Issue by berge459** [Qata/BarMagnet#45]
I don't own a domain and use No-IP Dynamic DNS for my site. I therefore cannot use Let's Encrypt to issue a cert that will be trusted. Due to this, I cannot connect using BarMagnet on iOS. Is there a way to connect to my Deluge server and manually "trust" the self-signed cert or is this a security restriction of the libraries used?

**Comment by JohnKis** [comment]
As long as the No-IP DNS record is up to date, you should be able to use Let’s Encrypt.

**Comment by berge459** [comment]
Yeah, you are correct. I was on a non standard port and had to use DNS based verification. Thanks for the inspiration to try with the cert again! You can close this issue.
