### ISSUE TITLE
info.plist missing

### ISSUE THREAD

**Issue by SJ50** [Qata/BarMagnet#48]
I am tried to sideload release ipa using cydia impactor but it gives error message that info.plist missing.

**Comment by niXta1** [comment]
Open the IPA with an archive app and rename the "payload" folder to "Payload". Save it, and it will work.

**Comment by niXta1** [comment]
That has to do with the signing process. Try to sign another app and see if you get the same error.

**Comment by SJ50** [comment]
now it worked for some reason. may be I was doing something wrong.
