### ISSUE TITLE
"Random" notifications

### ISSUE THREAD

**Issue by niccolospa** [Qata/BarMagnet#50]
I was glad to discover that the app also sends notifications when a torrent download is completed. The problem is that this happens randomly and not for all torrents. Is it an iOS background refresh related issue?

**Comment by Qata** [comment]
Yes, the OS schedules background refreshes. Nothing can be done except if you use the app more frequently, it’ll get more background refreshes.

**Comment by niccolospa** [comment]
Is this not possible to fix still?
