### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by 3mru** [Qata/BarMagnet#57]
Any chance for a dark mode here? The plain white UI is killing my eyes.

Thanks

**Comment by Qata** [comment]
I’m planning to rewrite it with SwiftUI later this year so that it can take advantage of automatic dark mode.

**Comment by 3mru** [comment]
Well that’s good news i guess. Definitely looking forward to it. Also would you please consider adding "Browse local files for .torrent” i think that’s a much needed feature too.

**Comment by Qata** [comment]
Oh yeah that’s a good suggestion too.
I could probably add that, but could you make a separate issue?

**Comment by 3mru** [comment]
Just submitted a new issue for that
Thank you for considering my suggestions :)

**Comment by Qata** [comment]
Good news! @rhysforyou is a gem and implemented dark mode.
